version: '3'
services:
  pairgoth:
    container_name: pairgoth-engine
    image: eclipse-temurin:18-jdk
    working_dir: /home/app/pairgoth
    user: "${APP_UID}:${APP_GID}"
    entrypoint: bash -c
    command: '"java -jar pairgoth-engine.jar"'
    volumes:
      - ./data/app:/home/app/pairgoth
      - ./data/jetty:/var/lib/pairgoth/jetty
    networks:
      - pairgoth-network
    ports:
     - '8080:8080'
    environment:
      HOME: "/home/app"
      USER: "app"
    stdin_open: true
    tty: true
networks:
  pairgoth-network:
    driver: bridge


